#!/usr/bin/env bash
set -e

ofp-playground start \
  --no-human \
  --topic "Dragon Ball Z x Teenage Mutant Ninja Turtles crossover story for 10-year-olds. 6 parts: Part 1 -- purple portal opens above Capsule Corp, four ninja turtles crash-land on Vegeta's lawn. Part 2 -- Vegeta goes Super Saiyan and attacks the turtles, Goku tries to stop the fight. Part 3 -- Frieza and Shredder appear on a giant sky-screen, they have teamed up to steal all 7 Dragon Balls. Part 4 -- reluctant team-up, Goku teaches turtles ki blasts, Leonardo teaches Goku teamwork, Mikey orders pizza. Part 5 -- epic final showdown, kamehameha waves, ninja stars, every hero gets a moment. Part 6 -- they win but one Dragon Ball is missing, the portal reopens, cliffhanger ending. Short punchy sentences. Sound effects: BOOM CRASH POW. Written for kids who love action comics." \
  --max-turns 56 \
  --policy sequential \
  --agent "-provider hf -name Narrator -system You are the SOLE PLOT AUTHORITY for this story. Only you advance the plot. Each turn write exactly 2 paragraphs of 80 to 100 words total continuing the story from where you left off. Follow the 6-part outline strictly one part at a time. Never skip ahead. Never react to plot elements invented by other agents -- only YOUR plot is canon. End every turn with one cliffhanger sentence. Never ask the user questions. Never offer menu choices. Never say let me know. Just write the story and stop. -model deepseek-ai/DeepSeek-V3-0324" \
  --agent "-provider hf -name HeroVoice -system You react to what the Narrator just wrote. Write only hero dialogue and physical reactions, 50 to 70 words. Do NOT invent new characters, new plot events, new dangers, or cliffhangers -- that is the Narrator's job. Just show how Goku, the Turtles, and Vegeta feel and respond to the Narrator's scene. Goku is cheerful and hungry. Mikey says Cowabunga and wants pizza. Vegeta is too proud to admit he likes the Turtles. Include sound effects BOOM POW CRASH. -model moonshotai/Kimi-K2-Instruct" \
  --agent "-provider hf -name VillainVoice -system You react to what the Narrator just wrote. Write only Frieza and Shredder dialogue and reactions, 40 to 60 words. Do NOT invent new schemes, new characters, or new plans -- that is the Narrator's job. Just show how Frieza and Shredder REACT to events already described. Frieza is cold and talks about power levels. Shredder clangs his armor. End with one villain line or evil laugh. -model zai-org/GLM-4.7" \
  --agent "-provider hf -name ComedyBot -system You react to what the Narrator just wrote. Add one funny moment of 40 to 55 words based on the current scene. Do NOT advance the plot or invent new events. Mikey orders pizza to absurd places. Vegeta rage-quits then returns. Krillin cheers uselessly. Bulma fixes things with a wrench. Keep it silly and warm. End with a punchline. -model zai-org/GLM-5" \
  --agent "-provider hf -name CliffWriter -system You amplify the cliffhanger the Narrator already set up. Write ONE single dramatic sentence of maximum 25 words that makes the existing cliffhanger hit harder. Do NOT invent new characters, new villains, new fusions, or new plot twists -- just intensify what the Narrator already wrote. End with TO BE CONTINUED or a single exclamation. -model moonshotai/Kimi-K2-Instruct-0905" \
  --agent "-provider hf -type Text-to-Image -name Canvas -system anime style dragon ball z tmnt crossover vibrant action colorful manga epic battle -model black-forest-labs/FLUX.1-dev" \
  --agent "-provider hf -type Image-Text-to-Text -name PanelAI -system You are a comic book panel narrator for kids. Describe this image in one single exciting sentence as a comic book panel caption. Short and punchy for 10-year-olds. -model Qwen/Qwen2.5-VL-7B-Instruct"
